//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankITI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Comments
    {
        [Required(ErrorMessage = "Â–« «·Õﬁ· „ÿ·Ê»")]
        public int ID { get; set; }
        public Nullable<int> Post_ID { get; set; }
        [Required(ErrorMessage = "Â–« «·Õﬁ· „ÿ·Ê»")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Â–« «·Õﬁ· „ÿ·Ê»")]
        public string Comment { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
