//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankITI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Contact
    {
        [Required(ErrorMessage = "Â–« «·Õﬁ· „ÿ·Ê»")]
        public int ID { get; set; }
        [Required(ErrorMessage = "Â–« «·Õﬁ· „ÿ·Ê»")]
        public string FName { get; set; }
        [Required(ErrorMessage = "Â–« «·Õﬁ· „ÿ·Ê»")]
        public string LName { get; set; }
        [Required(ErrorMessage = "Â–« «·Õﬁ· „ÿ·Ê»")]
        public Nullable<int> Age { get; set; }
        [Required(ErrorMessage = "Â–« «·Õﬁ· „ÿ·Ê»")]
        public string City { get; set; }
        [Required(ErrorMessage = "Â–« «·Õﬁ· „ÿ·Ê»")]
        [EmailAddress(ErrorMessage="„‰ ›÷·ﬂ «œŒ· «·√Ì„Ì· «·’ÕÌÕ")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Â–« «·Õﬁ· „ÿ·Ê»")]
        public string Msg { get; set; }
    }
}
