//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankITI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Location
    {
        public Location()
        {
            this.Donors = new HashSet<Donor>();
        }
    
        [Required]
        public int LID { get; set; }
        [Required]
        public Nullable<int> CID { get; set; }
        [Required]
        public string LocationName { get; set; }
    
        public virtual City City { get; set; }
        public virtual ICollection<Donor> Donors { get; set; }
    }
}
