//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankITI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Needer_Donor
    {
        [Required]
        public int NDID { get; set; }
        [Required]
        public int NID { get; set; }
        [Required]
        public int BID { get; set; }
        [Required]
        public int CID { get; set; }
        [Required]
        public int DID { get; set; }
        [Required]
        public System.DateTime AskDate { get; set; }
        public Nullable<bool> Accepted { get; set; }
    
        public virtual BloodType BloodType { get; set; }
        public virtual City City { get; set; }
        public virtual Donor Donor { get; set; }
        public virtual Needer Needer { get; set; }
    }
}
