//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankITI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Needer
    {
        public Needer()
        {
            this.Needer_Donor = new HashSet<Needer_Donor>();
        }
    
        public int NID { get; set; }
        public string Email { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public int BID { get; set; }
        public int CID { get; set; }
        public string Phone { get; set; }
    
        public virtual BloodType BloodType { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<Needer_Donor> Needer_Donor { get; set; }
    }
}
