//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankITI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comments>();
        }

        [Required]        
        public int PID { get; set; }
        [Required]
        public string Post1 { get; set; }
        [Required]
        public Nullable<System.DateTime> Insert_date { get; set; }
        [Required]
        [Phone]
        public string Phone { get; set; }
        [Required]
        public int BID { get; set; }
        [Required]
        public int CID { get; set; }
        [Required]
        public string Name { get; set; }
        public bool Periodic { get; set; }
    
        public virtual BloodType BloodType { get; set; }
        public virtual City City { get; set; }
        public virtual ICollection<Comments> Comments { get; set; }
    }
}
