//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankITI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UserType
    {
        public UserType()
        {
            this.Logins = new HashSet<Login>();
        }

        [Required(ErrorMessage = "Â–« «·Õﬁ· „ÿ·Ê»")]
        public string Type { get; set; }
        [Required(ErrorMessage = "Â–« «·Õﬁ· „ÿ·Ê»")]
        public int UTID { get; set; }
    
        public virtual ICollection<Login> Logins { get; set; }
    }
}
