//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public Nullable<int> Age { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string Msg { get; set; }
    }
}
