//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donor()
        {
            this.PartnersStatestics = new HashSet<PartnersStatestic>();
        }
    
        public int DID { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string DonorGender { get; set; }
        public string Phone { get; set; }
        public int BID { get; set; }
        public int CID { get; set; }
        public int LID { get; set; }
        public bool Status { get; set; }
        public bool Pending { get; set; }
        public Nullable<System.DateTime> DonationDate { get; set; }
        public Nullable<int> PAID { get; set; }
        public Nullable<bool> PhoneStatus { get; set; }
    
        public virtual BloodType BloodType { get; set; }
        public virtual City City { get; set; }
        public virtual Location Location { get; set; }
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnersStatestic> PartnersStatestics { get; set; }
    }
}
