//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankService.Models
{
    using System;
    using System.Collections.Generic;
    public partial class Login
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public int UID { get; set; }
        public int UTID { get; set; }
        public bool Status { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
